package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u8be2\u4ef7<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3291</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcForQuoteField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(2) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u8be2\u4ef7\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > ForQuoteRef() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(4) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u672c\u5730\u8be2\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcOrderLocalIDType
	 */
	@Array({13}) 
	@Field(5) 
	public Pointer<Byte > ForQuoteLocalID() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({11}) 
	@Field(7) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u5ba2\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({11}) 
	@Field(8) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u5408\u7ea6\u5728\u4ea4\u6613\u6240\u7684\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeInstIDType
	 */
	@Array({31}) 
	@Field(9) 
	public Pointer<Byte > ExchangeInstID() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \u4ea4\u6613\u6240\u4ea4\u6613\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcTraderIDType
	 */
	@Array({21}) 
	@Field(10) 
	public Pointer<Byte > TraderID() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(11) 
	public int InstallID() {
		return this.io.getIntField(this, 11);
	}
	/**
	 * \u5b89\u88c5\u7f16\u53f7<br>
	 * C type : TThostFtdcInstallIDType
	 */
	@Field(11) 
	public CThostFtdcForQuoteField InstallID(int InstallID) {
		this.io.setIntField(this, 11, InstallID);
		return this;
	}
	/**
	 * \u62a5\u5355\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(12) 
	public Pointer<Byte > InsertDate() {
		return this.io.getPointerField(this, 12);
	}
	/**
	 * \u63d2\u5165\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(13) 
	public Pointer<Byte > InsertTime() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * \u8be2\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcForQuoteStatusType
	 */
	@Field(14) 
	public byte ForQuoteStatus() {
		return this.io.getByteField(this, 14);
	}
	/**
	 * \u8be2\u4ef7\u72b6\u6001<br>
	 * C type : TThostFtdcForQuoteStatusType
	 */
	@Field(14) 
	public CThostFtdcForQuoteField ForQuoteStatus(byte ForQuoteStatus) {
		this.io.setByteField(this, 14, ForQuoteStatus);
		return this;
	}
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(15) 
	public int FrontID() {
		return this.io.getIntField(this, 15);
	}
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(15) 
	public CThostFtdcForQuoteField FrontID(int FrontID) {
		this.io.setIntField(this, 15, FrontID);
		return this;
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(16) 
	public int SessionID() {
		return this.io.getIntField(this, 16);
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(16) 
	public CThostFtdcForQuoteField SessionID(int SessionID) {
		this.io.setIntField(this, 16, SessionID);
		return this;
	}
	/**
	 * \u72b6\u6001\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({81}) 
	@Field(17) 
	public Pointer<Byte > StatusMsg() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * \u64cd\u4f5c\u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(18) 
	public Pointer<Byte > ActiveUserID() {
		return this.io.getPointerField(this, 18);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u8be2\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(19) 
	public int BrokerForQutoSeq() {
		return this.io.getIntField(this, 19);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u8be2\u4ef7\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(19) 
	public CThostFtdcForQuoteField BrokerForQutoSeq(int BrokerForQutoSeq) {
		this.io.setIntField(this, 19, BrokerForQutoSeq);
		return this;
	}
	/**
	 * \u6295\u8d44\u5355\u5143\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestUnitIDType
	 */
	@Array({17}) 
	@Field(20) 
	public Pointer<Byte > InvestUnitID() {
		return this.io.getPointerField(this, 20);
	}
	/**
	 * IP\u5730\u5740<br>
	 * C type : TThostFtdcIPAddressType
	 */
	@Array({16}) 
	@Field(21) 
	public Pointer<Byte > IPAddress() {
		return this.io.getPointerField(this, 21);
	}
	/**
	 * Mac\u5730\u5740<br>
	 * C type : TThostFtdcMacAddressType
	 */
	@Array({21}) 
	@Field(22) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 22);
	}
	public CThostFtdcForQuoteField() {
		super();
	}
	public CThostFtdcForQuoteField(Pointer pointer) {
		super(pointer);
	}
}
