package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4ea4\u6613\u6240\u4fdd\u8bc1\u91d1\u7387\u8c03\u6574<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:1038</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcExchangeMarginRateAdjustField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(1) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(2) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(2) 
	public CThostFtdcExchangeMarginRateAdjustField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 2, HedgeFlag);
		return this;
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(3) 
	public double LongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(3) 
	public CThostFtdcExchangeMarginRateAdjustField LongMarginRatioByMoney(double LongMarginRatioByMoney) {
		this.io.setDoubleField(this, 3, LongMarginRatioByMoney);
		return this;
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public double LongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public CThostFtdcExchangeMarginRateAdjustField LongMarginRatioByVolume(double LongMarginRatioByVolume) {
		this.io.setDoubleField(this, 4, LongMarginRatioByVolume);
		return this;
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public double ShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public CThostFtdcExchangeMarginRateAdjustField ShortMarginRatioByMoney(double ShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 5, ShortMarginRatioByMoney);
		return this;
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public double ShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public CThostFtdcExchangeMarginRateAdjustField ShortMarginRatioByVolume(double ShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 6, ShortMarginRatioByVolume);
		return this;
	}
	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7) 
	public double ExchLongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 7);
	}
	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7) 
	public CThostFtdcExchangeMarginRateAdjustField ExchLongMarginRatioByMoney(double ExchLongMarginRatioByMoney) {
		this.io.setDoubleField(this, 7, ExchLongMarginRatioByMoney);
		return this;
	}
	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public double ExchLongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 8);
	}
	/**
	 * \u4ea4\u6613\u6240\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public CThostFtdcExchangeMarginRateAdjustField ExchLongMarginRatioByVolume(double ExchLongMarginRatioByVolume) {
		this.io.setDoubleField(this, 8, ExchLongMarginRatioByVolume);
		return this;
	}
	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(9) 
	public double ExchShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 9);
	}
	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(9) 
	public CThostFtdcExchangeMarginRateAdjustField ExchShortMarginRatioByMoney(double ExchShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 9, ExchShortMarginRatioByMoney);
		return this;
	}
	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public double ExchShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 10);
	}
	/**
	 * \u4ea4\u6613\u6240\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public CThostFtdcExchangeMarginRateAdjustField ExchShortMarginRatioByVolume(double ExchShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 10, ExchShortMarginRatioByVolume);
		return this;
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(11) 
	public double NoLongMarginRatioByMoney() {
		return this.io.getDoubleField(this, 11);
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(11) 
	public CThostFtdcExchangeMarginRateAdjustField NoLongMarginRatioByMoney(double NoLongMarginRatioByMoney) {
		this.io.setDoubleField(this, 11, NoLongMarginRatioByMoney);
		return this;
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(12) 
	public double NoLongMarginRatioByVolume() {
		return this.io.getDoubleField(this, 12);
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u591a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(12) 
	public CThostFtdcExchangeMarginRateAdjustField NoLongMarginRatioByVolume(double NoLongMarginRatioByVolume) {
		this.io.setDoubleField(this, 12, NoLongMarginRatioByVolume);
		return this;
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(13) 
	public double NoShortMarginRatioByMoney() {
		return this.io.getDoubleField(this, 13);
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(13) 
	public CThostFtdcExchangeMarginRateAdjustField NoShortMarginRatioByMoney(double NoShortMarginRatioByMoney) {
		this.io.setDoubleField(this, 13, NoShortMarginRatioByMoney);
		return this;
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(14) 
	public double NoShortMarginRatioByVolume() {
		return this.io.getDoubleField(this, 14);
	}
	/**
	 * \u4e0d\u8ddf\u968f\u4ea4\u6613\u6240\u6295\u8d44\u8005\u7a7a\u5934\u4fdd\u8bc1\u91d1\u8d39<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(14) 
	public CThostFtdcExchangeMarginRateAdjustField NoShortMarginRatioByVolume(double NoShortMarginRatioByVolume) {
		this.io.setDoubleField(this, 14, NoShortMarginRatioByVolume);
		return this;
	}
	public CThostFtdcExchangeMarginRateAdjustField() {
		super();
	}
	public CThostFtdcExchangeMarginRateAdjustField(Pointer pointer) {
		super(pointer);
	}
}
