package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u67e5\u8be2\u94f6\u884c\u4ea4\u6613\u660e\u7ec6\u8bf7\u6c42\uff0cTradeCode=204999<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:259</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcTransferQryDetailReqField extends StructObject {
	/**
	 * \u671f\u8d27\u8d44\u91d1\u8d26\u6237<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({13}) 
	@Field(0) 
	public Pointer<Byte > FutureAccount() {
		return this.io.getPointerField(this, 0);
	}
	public CThostFtdcTransferQryDetailReqField() {
		super();
	}
	public CThostFtdcTransferQryDetailReqField(Pointer pointer) {
		super(pointer);
	}
}
