package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u67e5\u8be2\u6c47\u7387<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2546</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcQryExchangeRateField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6e90\u5e01\u79cd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(1) 
	public Pointer<Byte > FromCurrencyID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u76ee\u6807\u5e01\u79cd<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(2) 
	public Pointer<Byte > ToCurrencyID() {
		return this.io.getPointerField(this, 2);
	}
	public CThostFtdcQryExchangeRateField() {
		super();
	}
	public CThostFtdcQryExchangeRateField(Pointer pointer) {
		super(pointer);
	}
}
