package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u624b\u5de5\u540c\u6b65\u7528\u6237\u52a8\u6001\u4ee4\u724c<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5808</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcManualSyncBrokerUserOTPField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u52a8\u6001\u4ee4\u724c\u7c7b\u578b<br>
	 * C type : TThostFtdcOTPTypeType
	 */
	@Field(2) 
	public byte OTPType() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \u52a8\u6001\u4ee4\u724c\u7c7b\u578b<br>
	 * C type : TThostFtdcOTPTypeType
	 */
	@Field(2) 
	public CThostFtdcManualSyncBrokerUserOTPField OTPType(byte OTPType) {
		this.io.setByteField(this, 2, OTPType);
		return this;
	}
	/**
	 * \u7b2c\u4e00\u4e2a\u52a8\u6001\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(3) 
	public Pointer<Byte > FirstOTP() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u7b2c\u4e8c\u4e2a\u52a8\u6001\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(4) 
	public Pointer<Byte > SecondOTP() {
		return this.io.getPointerField(this, 4);
	}
	public CThostFtdcManualSyncBrokerUserOTPField() {
		super();
	}
	public CThostFtdcManualSyncBrokerUserOTPField(Pointer pointer) {
		super(pointer);
	}
}
