package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u7528\u6237\u6743\u9650<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4764</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcUserRightField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(1) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u5ba2\u6237\u6743\u9650\u7c7b\u578b<br>
	 * C type : TThostFtdcUserRightTypeType
	 */
	@Field(2) 
	public byte UserRightType() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \u5ba2\u6237\u6743\u9650\u7c7b\u578b<br>
	 * C type : TThostFtdcUserRightTypeType
	 */
	@Field(2) 
	public CThostFtdcUserRightField UserRightType(byte UserRightType) {
		this.io.setByteField(this, 2, UserRightType);
		return this;
	}
	/**
	 * \u662f\u5426\u7981\u6b62<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(3) 
	public int IsForbidden() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * \u662f\u5426\u7981\u6b62<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(3) 
	public CThostFtdcUserRightField IsForbidden(int IsForbidden) {
		this.io.setIntField(this, 3, IsForbidden);
		return this;
	}
	public CThostFtdcUserRightField() {
		super();
	}
	public CThostFtdcUserRightField(Pointer pointer) {
		super(pointer);
	}
}
