package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u67e5\u8be2\u4ea4\u6613\u7f16\u7801<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:2280</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcQryTradingCodeField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u5ba2\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcClientIDType
	 */
	@Array({11}) 
	@Field(3) 
	public Pointer<Byte > ClientID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u4ea4\u6613\u7f16\u7801\u7c7b\u578b<br>
	 * C type : TThostFtdcClientIDTypeType
	 */
	@Field(4) 
	public byte ClientIDType() {
		return this.io.getByteField(this, 4);
	}
	/**
	 * \u4ea4\u6613\u7f16\u7801\u7c7b\u578b<br>
	 * C type : TThostFtdcClientIDTypeType
	 */
	@Field(4) 
	public CThostFtdcQryTradingCodeField ClientIDType(byte ClientIDType) {
		this.io.setByteField(this, 4, ClientIDType);
		return this;
	}
	public CThostFtdcQryTradingCodeField() {
		super();
	}
	public CThostFtdcQryTradingCodeField(Pointer pointer) {
		super(pointer);
	}
}
