package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u7ecf\u7eaa\u516c\u53f8\u53ef\u63d0\u8d44\u91d1\u7b97\u6cd5\u8868<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5203</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcInvestorWithdrawAlgorithmField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public CThostFtdcInvestorWithdrawAlgorithmField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(2) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u53ef\u63d0\u8d44\u91d1\u6bd4\u4f8b<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(3) 
	public double UsingRatio() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u53ef\u63d0\u8d44\u91d1\u6bd4\u4f8b<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(3) 
	public CThostFtdcInvestorWithdrawAlgorithmField UsingRatio(double UsingRatio) {
		this.io.setDoubleField(this, 3, UsingRatio);
		return this;
	}
	/**
	 * \u5e01\u79cd\u4ee3\u7801<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(4) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u8d27\u5e01\u8d28\u62bc\u6bd4\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public double FundMortgageRatio() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u8d27\u5e01\u8d28\u62bc\u6bd4\u7387<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public CThostFtdcInvestorWithdrawAlgorithmField FundMortgageRatio(double FundMortgageRatio) {
		this.io.setDoubleField(this, 5, FundMortgageRatio);
		return this;
	}
	public CThostFtdcInvestorWithdrawAlgorithmField() {
		super();
	}
	public CThostFtdcInvestorWithdrawAlgorithmField(Pointer pointer) {
		super(pointer);
	}
}
