package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u7ecf\u7eaa\u516c\u53f8<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:425</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcBrokerField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u7b80\u79f0<br>
	 * C type : TThostFtdcBrokerAbbrType
	 */
	@Array({9}) 
	@Field(1) 
	public Pointer<Byte > BrokerAbbr() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u540d\u79f0<br>
	 * C type : TThostFtdcBrokerNameType
	 */
	@Array({81}) 
	@Field(2) 
	public Pointer<Byte > BrokerName() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u662f\u5426\u6d3b\u8dc3<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(3) 
	public int IsActive() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * \u662f\u5426\u6d3b\u8dc3<br>
	 * C type : TThostFtdcBoolType
	 */
	@Field(3) 
	public CThostFtdcBrokerField IsActive(int IsActive) {
		this.io.setIntField(this, 3, IsActive);
		return this;
	}
	public CThostFtdcBrokerField() {
		super();
	}
	public CThostFtdcBrokerField(Pointer pointer) {
		super(pointer);
	}
}
