package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4fdd\u8bc1\u91d1\u76d1\u7ba1\u7cfb\u7edf\u7ecf\u7eaa\u516c\u53f8\u5bc6\u94a5<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5744</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcCFMMCBrokerKeyField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u7edf\u4e00\u7f16\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u5bc6\u94a5\u751f\u6210\u65e5\u671f<br>
	 * C type : TThostFtdcDateType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > CreateDate() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u5bc6\u94a5\u751f\u6210\u65f6\u95f4<br>
	 * C type : TThostFtdcTimeType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > CreateTime() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u5bc6\u94a5\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(4) 
	public int KeyID() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \u5bc6\u94a5\u7f16\u53f7<br>
	 * C type : TThostFtdcSequenceNoType
	 */
	@Field(4) 
	public CThostFtdcCFMMCBrokerKeyField KeyID(int KeyID) {
		this.io.setIntField(this, 4, KeyID);
		return this;
	}
	/**
	 * \u52a8\u6001\u5bc6\u94a5<br>
	 * C type : TThostFtdcCFMMCKeyType
	 */
	@Array({21}) 
	@Field(5) 
	public Pointer<Byte > CurrentKey() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u52a8\u6001\u5bc6\u94a5\u7c7b\u578b<br>
	 * C type : TThostFtdcCFMMCKeyKindType
	 */
	@Field(6) 
	public byte KeyKind() {
		return this.io.getByteField(this, 6);
	}
	/**
	 * \u52a8\u6001\u5bc6\u94a5\u7c7b\u578b<br>
	 * C type : TThostFtdcCFMMCKeyKindType
	 */
	@Field(6) 
	public CThostFtdcCFMMCBrokerKeyField KeyKind(byte KeyKind) {
		this.io.setByteField(this, 6, KeyKind);
		return this;
	}
	public CThostFtdcCFMMCBrokerKeyField() {
		super();
	}
	public CThostFtdcCFMMCBrokerKeyField(Pointer pointer) {
		super(pointer);
	}
}
