package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u5f53\u524d\u62a5\u5355\u624b\u7eed\u8d39\u7684\u8be6\u7ec6\u5185\u5bb9<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4296</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcInstrumentOrderCommRateField extends StructObject {
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(0) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public byte InvestorRange() {
		return this.io.getByteField(this, 1);
	}
	/**
	 * \u6295\u8d44\u8005\u8303\u56f4<br>
	 * C type : TThostFtdcInvestorRangeType
	 */
	@Field(1) 
	public CThostFtdcInstrumentOrderCommRateField InvestorRange(byte InvestorRange) {
		this.io.setByteField(this, 1, InvestorRange);
		return this;
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(4) 
	public byte HedgeFlag() {
		return this.io.getByteField(this, 4);
	}
	/**
	 * \u6295\u673a\u5957\u4fdd\u6807\u5fd7<br>
	 * C type : TThostFtdcHedgeFlagType
	 */
	@Field(4) 
	public CThostFtdcInstrumentOrderCommRateField HedgeFlag(byte HedgeFlag) {
		this.io.setByteField(this, 4, HedgeFlag);
		return this;
	}
	/**
	 * \u62a5\u5355\u624b\u7eed\u8d39<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public double OrderCommByVolume() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u62a5\u5355\u624b\u7eed\u8d39<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(5) 
	public CThostFtdcInstrumentOrderCommRateField OrderCommByVolume(double OrderCommByVolume) {
		this.io.setDoubleField(this, 5, OrderCommByVolume);
		return this;
	}
	/**
	 * \u64a4\u5355\u624b\u7eed\u8d39<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(6) 
	public double OrderActionCommByVolume() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u64a4\u5355\u624b\u7eed\u8d39<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(6) 
	public CThostFtdcInstrumentOrderCommRateField OrderActionCommByVolume(double OrderActionCommByVolume) {
		this.io.setDoubleField(this, 6, OrderActionCommByVolume);
		return this;
	}
	public CThostFtdcInstrumentOrderCommRateField() {
		super();
	}
	public CThostFtdcInstrumentOrderCommRateField(Pointer pointer) {
		super(pointer);
	}
}
