package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u9519\u8bef\u6267\u884c\u5ba3\u544a\u64cd\u4f5c<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:3190</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcErrExecOrderActionField extends StructObject {
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(0) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u6295\u8d44\u8005\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestorIDType
	 */
	@Array({13}) 
	@Field(1) 
	public Pointer<Byte > InvestorID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u6267\u884c\u5ba3\u544a\u64cd\u4f5c\u5f15\u7528<br>
	 * C type : TThostFtdcOrderActionRefType
	 */
	@Field(2) 
	public int ExecOrderActionRef() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * \u6267\u884c\u5ba3\u544a\u64cd\u4f5c\u5f15\u7528<br>
	 * C type : TThostFtdcOrderActionRefType
	 */
	@Field(2) 
	public CThostFtdcErrExecOrderActionField ExecOrderActionRef(int ExecOrderActionRef) {
		this.io.setIntField(this, 2, ExecOrderActionRef);
		return this;
	}
	/**
	 * \u6267\u884c\u5ba3\u544a\u5f15\u7528<br>
	 * C type : TThostFtdcOrderRefType
	 */
	@Array({13}) 
	@Field(3) 
	public Pointer<Byte > ExecOrderRef() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(4) 
	public int RequestID() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * \u8bf7\u6c42\u7f16\u53f7<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(4) 
	public CThostFtdcErrExecOrderActionField RequestID(int RequestID) {
		this.io.setIntField(this, 4, RequestID);
		return this;
	}
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(5) 
	public int FrontID() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * \u524d\u7f6e\u7f16\u53f7<br>
	 * C type : TThostFtdcFrontIDType
	 */
	@Field(5) 
	public CThostFtdcErrExecOrderActionField FrontID(int FrontID) {
		this.io.setIntField(this, 5, FrontID);
		return this;
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(6) 
	public int SessionID() {
		return this.io.getIntField(this, 6);
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(6) 
	public CThostFtdcErrExecOrderActionField SessionID(int SessionID) {
		this.io.setIntField(this, 6, SessionID);
		return this;
	}
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(7) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u6267\u884c\u5ba3\u544a\u64cd\u4f5c\u7f16\u53f7<br>
	 * C type : TThostFtdcExecOrderSysIDType
	 */
	@Array({21}) 
	@Field(8) 
	public Pointer<Byte > ExecOrderSysID() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u64cd\u4f5c\u6807\u5fd7<br>
	 * C type : TThostFtdcActionFlagType
	 */
	@Field(9) 
	public byte ActionFlag() {
		return this.io.getByteField(this, 9);
	}
	/**
	 * \u64cd\u4f5c\u6807\u5fd7<br>
	 * C type : TThostFtdcActionFlagType
	 */
	@Field(9) 
	public CThostFtdcErrExecOrderActionField ActionFlag(byte ActionFlag) {
		this.io.setByteField(this, 9, ActionFlag);
		return this;
	}
	/**
	 * \u7528\u6237\u4ee3\u7801<br>
	 * C type : TThostFtdcUserIDType
	 */
	@Array({16}) 
	@Field(10) 
	public Pointer<Byte > UserID() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \u5408\u7ea6\u4ee3\u7801<br>
	 * C type : TThostFtdcInstrumentIDType
	 */
	@Array({31}) 
	@Field(11) 
	public Pointer<Byte > InstrumentID() {
		return this.io.getPointerField(this, 11);
	}
	/**
	 * \u6295\u8d44\u5355\u5143\u4ee3\u7801<br>
	 * C type : TThostFtdcInvestUnitIDType
	 */
	@Array({17}) 
	@Field(12) 
	public Pointer<Byte > InvestUnitID() {
		return this.io.getPointerField(this, 12);
	}
	/**
	 * IP\u5730\u5740<br>
	 * C type : TThostFtdcIPAddressType
	 */
	@Array({16}) 
	@Field(13) 
	public Pointer<Byte > IPAddress() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * Mac\u5730\u5740<br>
	 * C type : TThostFtdcMacAddressType
	 */
	@Array({21}) 
	@Field(14) 
	public Pointer<Byte > MacAddress() {
		return this.io.getPointerField(this, 14);
	}
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(15) 
	public int ErrorID() {
		return this.io.getIntField(this, 15);
	}
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(15) 
	public CThostFtdcErrExecOrderActionField ErrorID(int ErrorID) {
		this.io.setIntField(this, 15, ErrorID);
		return this;
	}
	/**
	 * \u9519\u8bef\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({81}) 
	@Field(16) 
	public Pointer<Byte > ErrorMsg() {
		return this.io.getPointerField(this, 16);
	}
	public CThostFtdcErrExecOrderActionField() {
		super();
	}
	public CThostFtdcErrExecOrderActionField(Pointer pointer) {
		super(pointer);
	}
}
