package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u7ecf\u7eaa\u516c\u53f8\u8d44\u91d1<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:5706</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcBrokerDepositField extends StructObject {
	/**
	 * \u4ea4\u6613\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u7ecf\u7eaa\u516c\u53f8\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(1) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u4f1a\u5458\u4ee3\u7801<br>
	 * C type : TThostFtdcParticipantIDType
	 */
	@Array({11}) 
	@Field(2) 
	public Pointer<Byte > ParticipantID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public double PreBalance() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \u4e0a\u6b21\u7ed3\u7b97\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(4) 
	public CThostFtdcBrokerDepositField PreBalance(double PreBalance) {
		this.io.setDoubleField(this, 4, PreBalance);
		return this;
	}
	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public double CurrMargin() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u5f53\u524d\u4fdd\u8bc1\u91d1\u603b\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(5) 
	public CThostFtdcBrokerDepositField CurrMargin(double CurrMargin) {
		this.io.setDoubleField(this, 5, CurrMargin);
		return this;
	}
	/**
	 * \u5e73\u4ed3\u76c8\u4e8f<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public double CloseProfit() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u5e73\u4ed3\u76c8\u4e8f<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(6) 
	public CThostFtdcBrokerDepositField CloseProfit(double CloseProfit) {
		this.io.setDoubleField(this, 6, CloseProfit);
		return this;
	}
	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7) 
	public double Balance() {
		return this.io.getDoubleField(this, 7);
	}
	/**
	 * \u671f\u8d27\u7ed3\u7b97\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(7) 
	public CThostFtdcBrokerDepositField Balance(double Balance) {
		this.io.setDoubleField(this, 7, Balance);
		return this;
	}
	/**
	 * \u5165\u91d1\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public double Deposit() {
		return this.io.getDoubleField(this, 8);
	}
	/**
	 * \u5165\u91d1\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(8) 
	public CThostFtdcBrokerDepositField Deposit(double Deposit) {
		this.io.setDoubleField(this, 8, Deposit);
		return this;
	}
	/**
	 * \u51fa\u91d1\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9) 
	public double Withdraw() {
		return this.io.getDoubleField(this, 9);
	}
	/**
	 * \u51fa\u91d1\u91d1\u989d<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(9) 
	public CThostFtdcBrokerDepositField Withdraw(double Withdraw) {
		this.io.setDoubleField(this, 9, Withdraw);
		return this;
	}
	/**
	 * \u53ef\u63d0\u8d44\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public double Available() {
		return this.io.getDoubleField(this, 10);
	}
	/**
	 * \u53ef\u63d0\u8d44\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(10) 
	public CThostFtdcBrokerDepositField Available(double Available) {
		this.io.setDoubleField(this, 10, Available);
		return this;
	}
	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(11) 
	public double Reserve() {
		return this.io.getDoubleField(this, 11);
	}
	/**
	 * \u57fa\u672c\u51c6\u5907\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(11) 
	public CThostFtdcBrokerDepositField Reserve(double Reserve) {
		this.io.setDoubleField(this, 11, Reserve);
		return this;
	}
	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(12) 
	public double FrozenMargin() {
		return this.io.getDoubleField(this, 12);
	}
	/**
	 * \u51bb\u7ed3\u7684\u4fdd\u8bc1\u91d1<br>
	 * C type : TThostFtdcMoneyType
	 */
	@Field(12) 
	public CThostFtdcBrokerDepositField FrozenMargin(double FrozenMargin) {
		this.io.setDoubleField(this, 12, FrozenMargin);
		return this;
	}
	public CThostFtdcBrokerDepositField() {
		super();
	}
	public CThostFtdcBrokerDepositField(Pointer pointer) {
		super(pointer);
	}
}
