package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u4ea4\u6613\u6240<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:308</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcExchangeField extends StructObject {
	/**
	 * \u4ea4\u6613\u6240\u4ee3\u7801<br>
	 * C type : TThostFtdcExchangeIDType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > ExchangeID() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u4ea4\u6613\u6240\u540d\u79f0<br>
	 * C type : TThostFtdcExchangeNameType
	 */
	@Array({61}) 
	@Field(1) 
	public Pointer<Byte > ExchangeName() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u4ea4\u6613\u6240\u5c5e\u6027<br>
	 * C type : TThostFtdcExchangePropertyType
	 */
	@Field(2) 
	public byte ExchangeProperty() {
		return this.io.getByteField(this, 2);
	}
	/**
	 * \u4ea4\u6613\u6240\u5c5e\u6027<br>
	 * C type : TThostFtdcExchangePropertyType
	 */
	@Field(2) 
	public CThostFtdcExchangeField ExchangeProperty(byte ExchangeProperty) {
		this.io.setByteField(this, 2, ExchangeProperty);
		return this;
	}
	public CThostFtdcExchangeField() {
		super();
	}
	public CThostFtdcExchangeField(Pointer pointer) {
		super(pointer);
	}
}
