package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u884c\u60c5\u9759\u6001\u5c5e\u6027<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4392</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcMarketDataStaticField extends StructObject {
	/**
	 * \u4eca\u5f00\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0) 
	public double OpenPrice() {
		return this.io.getDoubleField(this, 0);
	}
	/**
	 * \u4eca\u5f00\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0) 
	public CThostFtdcMarketDataStaticField OpenPrice(double OpenPrice) {
		this.io.setDoubleField(this, 0, OpenPrice);
		return this;
	}
	/**
	 * \u6700\u9ad8\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(1) 
	public double HighestPrice() {
		return this.io.getDoubleField(this, 1);
	}
	/**
	 * \u6700\u9ad8\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(1) 
	public CThostFtdcMarketDataStaticField HighestPrice(double HighestPrice) {
		this.io.setDoubleField(this, 1, HighestPrice);
		return this;
	}
	/**
	 * \u6700\u4f4e\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2) 
	public double LowestPrice() {
		return this.io.getDoubleField(this, 2);
	}
	/**
	 * \u6700\u4f4e\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2) 
	public CThostFtdcMarketDataStaticField LowestPrice(double LowestPrice) {
		this.io.setDoubleField(this, 2, LowestPrice);
		return this;
	}
	/**
	 * \u4eca\u6536\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public double ClosePrice() {
		return this.io.getDoubleField(this, 3);
	}
	/**
	 * \u4eca\u6536\u76d8<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(3) 
	public CThostFtdcMarketDataStaticField ClosePrice(double ClosePrice) {
		this.io.setDoubleField(this, 3, ClosePrice);
		return this;
	}
	/**
	 * \u6da8\u505c\u677f\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public double UpperLimitPrice() {
		return this.io.getDoubleField(this, 4);
	}
	/**
	 * \u6da8\u505c\u677f\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(4) 
	public CThostFtdcMarketDataStaticField UpperLimitPrice(double UpperLimitPrice) {
		this.io.setDoubleField(this, 4, UpperLimitPrice);
		return this;
	}
	/**
	 * \u8dcc\u505c\u677f\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5) 
	public double LowerLimitPrice() {
		return this.io.getDoubleField(this, 5);
	}
	/**
	 * \u8dcc\u505c\u677f\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(5) 
	public CThostFtdcMarketDataStaticField LowerLimitPrice(double LowerLimitPrice) {
		this.io.setDoubleField(this, 5, LowerLimitPrice);
		return this;
	}
	/**
	 * \u672c\u6b21\u7ed3\u7b97\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public double SettlementPrice() {
		return this.io.getDoubleField(this, 6);
	}
	/**
	 * \u672c\u6b21\u7ed3\u7b97\u4ef7<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(6) 
	public CThostFtdcMarketDataStaticField SettlementPrice(double SettlementPrice) {
		this.io.setDoubleField(this, 6, SettlementPrice);
		return this;
	}
	/**
	 * \u4eca\u865a\u5b9e\u5ea6<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7) 
	public double CurrDelta() {
		return this.io.getDoubleField(this, 7);
	}
	/**
	 * \u4eca\u865a\u5b9e\u5ea6<br>
	 * C type : TThostFtdcRatioType
	 */
	@Field(7) 
	public CThostFtdcMarketDataStaticField CurrDelta(double CurrDelta) {
		this.io.setDoubleField(this, 7, CurrDelta);
		return this;
	}
	public CThostFtdcMarketDataStaticField() {
		super();
	}
	public CThostFtdcMarketDataStaticField(Pointer pointer) {
		super(pointer);
	}
}
