package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u67e5\u8be2\u6307\u5b9a\u6d41\u6c34\u53f7\u7684\u4ea4\u6613\u7ed3\u679c\u54cd\u5e94<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:7163</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcRspQueryTradeResultBySerialField extends StructObject {
	/**
	 * \u4e1a\u52a1\u529f\u80fd\u7801<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	@Array({7}) 
	@Field(0) 
	public Pointer<Byte > TradeCode() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u94f6\u884c\u4ee3\u7801<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({4}) 
	@Field(1) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u94f6\u884c\u5206\u652f\u673a\u6784\u4ee3\u7801<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	@Array({5}) 
	@Field(2) 
	public Pointer<Byte > BankBranchID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u671f\u5546\u4ee3\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(3) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u671f\u5546\u5206\u652f\u673a\u6784\u4ee3\u7801<br>
	 * C type : TThostFtdcFutureBranchIDType
	 */
	@Array({31}) 
	@Field(4) 
	public Pointer<Byte > BrokerBranchID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u4ea4\u6613\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(5) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u4ea4\u6613\u65f6\u95f4<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	@Array({9}) 
	@Field(6) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \u94f6\u884c\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcBankSerialType
	 */
	@Array({13}) 
	@Field(7) 
	public Pointer<Byte > BankSerial() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u4ea4\u6613\u7cfb\u7edf\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(8) 
	public Pointer<Byte > TradingDay() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(9) 
	public int PlateSerial() {
		return this.io.getIntField(this, 9);
	}
	/**
	 * \u94f6\u671f\u5e73\u53f0\u6d88\u606f\u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(9) 
	public CThostFtdcRspQueryTradeResultBySerialField PlateSerial(int PlateSerial) {
		this.io.setIntField(this, 9, PlateSerial);
		return this;
	}
	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7<br>
	 * C type : TThostFtdcLastFragmentType
	 */
	@Field(10) 
	public byte LastFragment() {
		return this.io.getByteField(this, 10);
	}
	/**
	 * \u6700\u540e\u5206\u7247\u6807\u5fd7<br>
	 * C type : TThostFtdcLastFragmentType
	 */
	@Field(10) 
	public CThostFtdcRspQueryTradeResultBySerialField LastFragment(byte LastFragment) {
		this.io.setByteField(this, 10, LastFragment);
		return this;
	}
	/**
	 * \u4f1a\u8bdd\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public int SessionID() {
		return this.io.getIntField(this, 11);
	}
	/**
	 * \u4f1a\u8bdd\u53f7<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public CThostFtdcRspQueryTradeResultBySerialField SessionID(int SessionID) {
		this.io.setIntField(this, 11, SessionID);
		return this;
	}
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(12) 
	public int ErrorID() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \u9519\u8bef\u4ee3\u7801<br>
	 * C type : TThostFtdcErrorIDType
	 */
	@Field(12) 
	public CThostFtdcRspQueryTradeResultBySerialField ErrorID(int ErrorID) {
		this.io.setIntField(this, 12, ErrorID);
		return this;
	}
	/**
	 * \u9519\u8bef\u4fe1\u606f<br>
	 * C type : TThostFtdcErrorMsgType
	 */
	@Array({81}) 
	@Field(13) 
	public Pointer<Byte > ErrorMsg() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * \u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(14) 
	public int Reference() {
		return this.io.getIntField(this, 14);
	}
	/**
	 * \u6d41\u6c34\u53f7<br>
	 * C type : TThostFtdcSerialType
	 */
	@Field(14) 
	public CThostFtdcRspQueryTradeResultBySerialField Reference(int Reference) {
		this.io.setIntField(this, 14, Reference);
		return this;
	}
	/**
	 * \u672c\u6d41\u6c34\u53f7\u53d1\u5e03\u8005\u7684\u673a\u6784\u7c7b\u578b<br>
	 * C type : TThostFtdcInstitutionTypeType
	 */
	@Field(15) 
	public byte RefrenceIssureType() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * \u672c\u6d41\u6c34\u53f7\u53d1\u5e03\u8005\u7684\u673a\u6784\u7c7b\u578b<br>
	 * C type : TThostFtdcInstitutionTypeType
	 */
	@Field(15) 
	public CThostFtdcRspQueryTradeResultBySerialField RefrenceIssureType(byte RefrenceIssureType) {
		this.io.setByteField(this, 15, RefrenceIssureType);
		return this;
	}
	/**
	 * \u672c\u6d41\u6c34\u53f7\u53d1\u5e03\u8005\u673a\u6784\u7f16\u7801<br>
	 * C type : TThostFtdcOrganCodeType
	 */
	@Array({36}) 
	@Field(16) 
	public Pointer<Byte > RefrenceIssure() {
		return this.io.getPointerField(this, 16);
	}
	/**
	 * \u539f\u59cb\u8fd4\u56de\u4ee3\u7801<br>
	 * C type : TThostFtdcReturnCodeType
	 */
	@Array({7}) 
	@Field(17) 
	public Pointer<Byte > OriginReturnCode() {
		return this.io.getPointerField(this, 17);
	}
	/**
	 * \u539f\u59cb\u8fd4\u56de\u7801\u63cf\u8ff0<br>
	 * C type : TThostFtdcDescrInfoForReturnCodeType
	 */
	@Array({129}) 
	@Field(18) 
	public Pointer<Byte > OriginDescrInfoForReturnCode() {
		return this.io.getPointerField(this, 18);
	}
	/**
	 * \u94f6\u884c\u5e10\u53f7<br>
	 * C type : TThostFtdcBankAccountType
	 */
	@Array({41}) 
	@Field(19) 
	public Pointer<Byte > BankAccount() {
		return this.io.getPointerField(this, 19);
	}
	/**
	 * \u94f6\u884c\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(20) 
	public Pointer<Byte > BankPassWord() {
		return this.io.getPointerField(this, 20);
	}
	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({13}) 
	@Field(21) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 21);
	}
	/**
	 * \u671f\u8d27\u5bc6\u7801<br>
	 * C type : TThostFtdcPasswordType
	 */
	@Array({41}) 
	@Field(22) 
	public Pointer<Byte > Password() {
		return this.io.getPointerField(this, 22);
	}
	/**
	 * \u5e01\u79cd\u4ee3\u7801<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(23) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 23);
	}
	/**
	 * \u8f6c\u5e10\u91d1\u989d<br>
	 * C type : TThostFtdcTradeAmountType
	 */
	@Field(24) 
	public double TradeAmount() {
		return this.io.getDoubleField(this, 24);
	}
	/**
	 * \u8f6c\u5e10\u91d1\u989d<br>
	 * C type : TThostFtdcTradeAmountType
	 */
	@Field(24) 
	public CThostFtdcRspQueryTradeResultBySerialField TradeAmount(double TradeAmount) {
		this.io.setDoubleField(this, 24, TradeAmount);
		return this;
	}
	/**
	 * \u6458\u8981<br>
	 * C type : TThostFtdcDigestType
	 */
	@Array({36}) 
	@Field(25) 
	public Pointer<Byte > Digest() {
		return this.io.getPointerField(this, 25);
	}
	public CThostFtdcRspQueryTradeResultBySerialField() {
		super();
	}
	public CThostFtdcRspQueryTradeResultBySerialField(Pointer pointer) {
		super(pointer);
	}
}
