package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u5ba2\u6237\u5f00\u9500\u6237\u4fe1\u606f\u8868<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:7785</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcAccountregisterField extends StructObject {
	/**
	 * \u4ea4\u6613\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(0) 
	public Pointer<Byte > TradeDay() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u94f6\u884c\u7f16\u7801<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({4}) 
	@Field(1) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u94f6\u884c\u5206\u652f\u673a\u6784\u7f16\u7801<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	@Array({5}) 
	@Field(2) 
	public Pointer<Byte > BankBranchID() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u94f6\u884c\u5e10\u53f7<br>
	 * C type : TThostFtdcBankAccountType
	 */
	@Array({41}) 
	@Field(3) 
	public Pointer<Byte > BankAccount() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u671f\u8d27\u516c\u53f8\u7f16\u7801<br>
	 * C type : TThostFtdcBrokerIDType
	 */
	@Array({11}) 
	@Field(4) 
	public Pointer<Byte > BrokerID() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u671f\u8d27\u516c\u53f8\u5206\u652f\u673a\u6784\u7f16\u7801<br>
	 * C type : TThostFtdcFutureBranchIDType
	 */
	@Array({31}) 
	@Field(5) 
	public Pointer<Byte > BrokerBranchID() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u6295\u8d44\u8005\u5e10\u53f7<br>
	 * C type : TThostFtdcAccountIDType
	 */
	@Array({13}) 
	@Field(6) 
	public Pointer<Byte > AccountID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \u8bc1\u4ef6\u7c7b\u578b<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	@Field(7) 
	public byte IdCardType() {
		return this.io.getByteField(this, 7);
	}
	/**
	 * \u8bc1\u4ef6\u7c7b\u578b<br>
	 * C type : TThostFtdcIdCardTypeType
	 */
	@Field(7) 
	public CThostFtdcAccountregisterField IdCardType(byte IdCardType) {
		this.io.setByteField(this, 7, IdCardType);
		return this;
	}
	/**
	 * \u8bc1\u4ef6\u53f7\u7801<br>
	 * C type : TThostFtdcIdentifiedCardNoType
	 */
	@Array({51}) 
	@Field(8) 
	public Pointer<Byte > IdentifiedCardNo() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u5ba2\u6237\u59d3\u540d<br>
	 * C type : TThostFtdcIndividualNameType
	 */
	@Array({51}) 
	@Field(9) 
	public Pointer<Byte > CustomerName() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \u5e01\u79cd\u4ee3\u7801<br>
	 * C type : TThostFtdcCurrencyIDType
	 */
	@Array({4}) 
	@Field(10) 
	public Pointer<Byte > CurrencyID() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \u5f00\u9500\u6237\u7c7b\u522b<br>
	 * C type : TThostFtdcOpenOrDestroyType
	 */
	@Field(11) 
	public byte OpenOrDestroy() {
		return this.io.getByteField(this, 11);
	}
	/**
	 * \u5f00\u9500\u6237\u7c7b\u522b<br>
	 * C type : TThostFtdcOpenOrDestroyType
	 */
	@Field(11) 
	public CThostFtdcAccountregisterField OpenOrDestroy(byte OpenOrDestroy) {
		this.io.setByteField(this, 11, OpenOrDestroy);
		return this;
	}
	/**
	 * \u7b7e\u7ea6\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(12) 
	public Pointer<Byte > RegDate() {
		return this.io.getPointerField(this, 12);
	}
	/**
	 * \u89e3\u7ea6\u65e5\u671f<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(13) 
	public Pointer<Byte > OutDate() {
		return this.io.getPointerField(this, 13);
	}
	/**
	 * \u4ea4\u6613ID<br>
	 * C type : TThostFtdcTIDType
	 */
	@Field(14) 
	public int TID() {
		return this.io.getIntField(this, 14);
	}
	/**
	 * \u4ea4\u6613ID<br>
	 * C type : TThostFtdcTIDType
	 */
	@Field(14) 
	public CThostFtdcAccountregisterField TID(int TID) {
		this.io.setIntField(this, 14, TID);
		return this;
	}
	/**
	 * \u5ba2\u6237\u7c7b\u578b<br>
	 * C type : TThostFtdcCustTypeType
	 */
	@Field(15) 
	public byte CustType() {
		return this.io.getByteField(this, 15);
	}
	/**
	 * \u5ba2\u6237\u7c7b\u578b<br>
	 * C type : TThostFtdcCustTypeType
	 */
	@Field(15) 
	public CThostFtdcAccountregisterField CustType(byte CustType) {
		this.io.setByteField(this, 15, CustType);
		return this;
	}
	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	@Field(16) 
	public byte BankAccType() {
		return this.io.getByteField(this, 16);
	}
	/**
	 * \u94f6\u884c\u5e10\u53f7\u7c7b\u578b<br>
	 * C type : TThostFtdcBankAccTypeType
	 */
	@Field(16) 
	public CThostFtdcAccountregisterField BankAccType(byte BankAccType) {
		this.io.setByteField(this, 16, BankAccType);
		return this;
	}
	/**
	 * \u957f\u5ba2\u6237\u59d3\u540d<br>
	 * C type : TThostFtdcLongIndividualNameType
	 */
	@Array({161}) 
	@Field(17) 
	public Pointer<Byte > LongCustomerName() {
		return this.io.getPointerField(this, 17);
	}
	public CThostFtdcAccountregisterField() {
		super();
	}
	public CThostFtdcAccountregisterField(Pointer pointer) {
		super(pointer);
	}
}
