package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u94f6\u671f\u8f6c\u5e10\u62a5\u6587\u5934<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:128</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcTransferHeaderField extends StructObject {
	/**
	 * \u7248\u672c\u53f7\uff0c\u5e38\u91cf\uff0c1.0<br>
	 * C type : TThostFtdcVersionType
	 */
	@Array({4}) 
	@Field(0) 
	public Pointer<Byte > Version() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * \u4ea4\u6613\u4ee3\u7801\uff0c\u5fc5\u586b<br>
	 * C type : TThostFtdcTradeCodeType
	 */
	@Array({7}) 
	@Field(1) 
	public Pointer<Byte > TradeCode() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * \u4ea4\u6613\u65e5\u671f\uff0c\u5fc5\u586b\uff0c\u683c\u5f0f\uff1ayyyymmdd<br>
	 * C type : TThostFtdcTradeDateType
	 */
	@Array({9}) 
	@Field(2) 
	public Pointer<Byte > TradeDate() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * \u4ea4\u6613\u65f6\u95f4\uff0c\u5fc5\u586b\uff0c\u683c\u5f0f\uff1ahhmmss<br>
	 * C type : TThostFtdcTradeTimeType
	 */
	@Array({9}) 
	@Field(3) 
	public Pointer<Byte > TradeTime() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * \u53d1\u8d77\u65b9\u6d41\u6c34\u53f7\uff0cN/A<br>
	 * C type : TThostFtdcTradeSerialType
	 */
	@Array({9}) 
	@Field(4) 
	public Pointer<Byte > TradeSerial() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * \u671f\u8d27\u516c\u53f8\u4ee3\u7801\uff0c\u5fc5\u586b<br>
	 * C type : TThostFtdcFutureIDType
	 */
	@Array({11}) 
	@Field(5) 
	public Pointer<Byte > FutureID() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * \u94f6\u884c\u4ee3\u7801\uff0c\u6839\u636e\u67e5\u8be2\u94f6\u884c\u5f97\u5230\uff0c\u5fc5\u586b<br>
	 * C type : TThostFtdcBankIDType
	 */
	@Array({4}) 
	@Field(6) 
	public Pointer<Byte > BankID() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * \u94f6\u884c\u5206\u4e2d\u5fc3\u4ee3\u7801\uff0c\u6839\u636e\u67e5\u8be2\u94f6\u884c\u5f97\u5230\uff0c\u5fc5\u586b<br>
	 * C type : TThostFtdcBankBrchIDType
	 */
	@Array({5}) 
	@Field(7) 
	public Pointer<Byte > BankBrchID() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * \u64cd\u4f5c\u5458\uff0cN/A<br>
	 * C type : TThostFtdcOperNoType
	 */
	@Array({17}) 
	@Field(8) 
	public Pointer<Byte > OperNo() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * \u4ea4\u6613\u8bbe\u5907\u7c7b\u578b\uff0cN/A<br>
	 * C type : TThostFtdcDeviceIDType
	 */
	@Array({3}) 
	@Field(9) 
	public Pointer<Byte > DeviceID() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * \u8bb0\u5f55\u6570\uff0cN/A<br>
	 * C type : TThostFtdcRecordNumType
	 */
	@Array({7}) 
	@Field(10) 
	public Pointer<Byte > RecordNum() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7\uff0cN/A<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public int SessionID() {
		return this.io.getIntField(this, 11);
	}
	/**
	 * \u4f1a\u8bdd\u7f16\u53f7\uff0cN/A<br>
	 * C type : TThostFtdcSessionIDType
	 */
	@Field(11) 
	public CThostFtdcTransferHeaderField SessionID(int SessionID) {
		this.io.setIntField(this, 11, SessionID);
		return this;
	}
	/**
	 * \u8bf7\u6c42\u7f16\u53f7\uff0cN/A<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(12) 
	public int RequestID() {
		return this.io.getIntField(this, 12);
	}
	/**
	 * \u8bf7\u6c42\u7f16\u53f7\uff0cN/A<br>
	 * C type : TThostFtdcRequestIDType
	 */
	@Field(12) 
	public CThostFtdcTransferHeaderField RequestID(int RequestID) {
		this.io.setIntField(this, 12, RequestID);
		return this;
	}
	public CThostFtdcTransferHeaderField() {
		super();
	}
	public CThostFtdcTransferHeaderField(Pointer pointer) {
		super(pointer);
	}
}
