package com.ctp.thostftdcuserapistruct;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \u884c\u60c5\u7533\u4e70\u56db\u3001\u4e94\u5c5e\u6027<br>
 * <i>native declaration : ThostFtdcUserApiStruct.h:4465</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
 
public class CThostFtdcMarketDataBid45Field extends StructObject {
	/**
	 * \u7533\u4e70\u4ef7\u56db<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0) 
	public double BidPrice4() {
		return this.io.getDoubleField(this, 0);
	}
	/**
	 * \u7533\u4e70\u4ef7\u56db<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(0) 
	public CThostFtdcMarketDataBid45Field BidPrice4(double BidPrice4) {
		this.io.setDoubleField(this, 0, BidPrice4);
		return this;
	}
	/**
	 * \u7533\u4e70\u91cf\u56db<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(1) 
	public int BidVolume4() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * \u7533\u4e70\u91cf\u56db<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(1) 
	public CThostFtdcMarketDataBid45Field BidVolume4(int BidVolume4) {
		this.io.setIntField(this, 1, BidVolume4);
		return this;
	}
	/**
	 * \u7533\u4e70\u4ef7\u4e94<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2) 
	public double BidPrice5() {
		return this.io.getDoubleField(this, 2);
	}
	/**
	 * \u7533\u4e70\u4ef7\u4e94<br>
	 * C type : TThostFtdcPriceType
	 */
	@Field(2) 
	public CThostFtdcMarketDataBid45Field BidPrice5(double BidPrice5) {
		this.io.setDoubleField(this, 2, BidPrice5);
		return this;
	}
	/**
	 * \u7533\u4e70\u91cf\u4e94<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(3) 
	public int BidVolume5() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * \u7533\u4e70\u91cf\u4e94<br>
	 * C type : TThostFtdcVolumeType
	 */
	@Field(3) 
	public CThostFtdcMarketDataBid45Field BidVolume5(int BidVolume5) {
		this.io.setIntField(this, 3, BidVolume5);
		return this;
	}
	public CThostFtdcMarketDataBid45Field() {
		super();
	}
	public CThostFtdcMarketDataBid45Field(Pointer pointer) {
		super(pointer);
	}
}
